export const ACCESS_TOKEN_STORAGE_KEY = 'accessToken';
export const REFRESH_TOKEN_STORAGE_KEY = 'refreshToken';

// FIXME: Get from the server
export const TOPIC_TAGS = [
  'JavaScript',
  'TypeScript',
  'web development',
  'back-end development',
  'front-end development',
  'software engineering',
  'Golang',
  'Node.js',
  'full-stack development',
  'python',
  'data analysis',
  'data visualisation',
  'SQL',
  'NoSQL',
  'Graph Database',
  'Databases',
  'data science',
  'C++',
  'C#',
  'Java',
  'Kotlin',
  'Android Development',
  'iOS development',
  'game development',
  'unreal game engine',
  'technical interview',
  'machine learning',
  'artificial intelligence',
  'natural language processing',
  'software testing',
  'Algorithms and Data Structures',
  'DevOps',
  'cybersecurity',
  'Operating Systems',
  'UI/UX design',
];
